STRUCTURE_BIOME = {
    "Accampamento disabitato": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Accampamento tribale": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Alberi a forma di portale": ["Foresta", "Montagna", "Collina", "Prateria", "Palude"],
    "Alberi colorati": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Alberi Morti": ["Foresta", "Montagna", "Collina", "Prateria", "Palude"],
    "Alberi rossi": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Alberi scintillanti": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Alberi spettrali": ["Foresta", "Montagna", "Collina", "Prateria", "Palude"],
    "Albero con impiccati": ["Foresta", "Montagna", "Collina", "Prateria", "Palude"],
    "Albero Enorme": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Alligatore impagliato": ["Palude"],
    "Altare cerimoniale": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Altare sacrificale": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Bandiera puntata": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Barca a remi abbandonata": ["Palude"],
    "Bolle verdi su alberi": ["Foresta", "Collina", "Prateria", "Palude"],
    "Boschetto isolato": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Cactus": ["Deserto"],
    "Campi bruciati": ["Collina", "Prateria"],
    "Campi coltivati": ["Collina", "Prateria"],
    "Campo di fiori": ["Foresta", "Montagna", "Collina", "Prateria", "Palude"],
    "Canne di bambù": ["Palude"],
    "Capanna di marzapane": ["Foresta", "Collina", "Prateria"],
    "Capanna inquietante con teschi": ["Palude"],
    "Carcassa Grande animale morto": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Cartello": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Casa con Camino che fuma": ["Foresta", "Montagna", "Collina", "Prateria", "Palude"],
    "Casa sull'Albero": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Cascata": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Case abband. sugli alberi": ["Collina", "Palude"],
    "Case abbandonata sugli alberi": ["Foresta"],
    "Case contadine": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Case fiabesche negli alberi": ["Foresta", "Collina", "Prateria"],
    "Catasta di Legna": ["Foresta", "Montagna", "Collina", "Prateria", "Palude"],
    "Cerchio di pietre": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Cimitero": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Disegni nel grano": ["Collina", "Prateria"],
    "Erba Mobile": ["Deserto"],
    "Falegnameria": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Forte": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Funghi giganti": ["Foresta", "Montagna", "Collina", "Prateria", "Palude"],
    "Giardino rigoglioso": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Graffiti": ["Montagna"],
    "Grande cancello": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Grande cratere": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Grande radura": ["Foresta", "Collina"],
    "Grande Roccia": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Grotta": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Labirinto di pietra e rampicanti": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Lago": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Lago putrefatto": ["Palude"],
    "Locanda disabitata": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Macchinari agricoli": ["Collina", "Prateria"],
    "Miniera": ["Montagna"],
    "Monastero": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Mulino": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Nido gigante": ["Foresta", "Montagna", "Collina"],
    "Oasi": ["Deserto"],
    "Opere di irrigazione": ["Collina", "Prateria"],
    "Orme Giganti": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Ossa di Animali": ["Deserto"],
    "Palafitte": ["Palude"],
    "Piramide": ["Deserto"],
    "Risaia": ["Prateria"],
    "Rocce colorate": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Rovine": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Ruscello": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Ruscello fatato": ["Foresta", "Montagna", "Collina", "Prateria"],
    "Scalinata": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Sfera luminosa che fluttua": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Sorgente": ["Foresta", "Montagna", "Collina"],
    "Spada Roccia": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Spaventapasseri": ["Foresta", "Montagna", "Collina", "Prateria", "Palude"],
    "Stalle": ["Montagna", "Collina", "Prateria"],
    "Statua enorme Di Pietra": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Statue dimenticate": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Strane pitture": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Tempio": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Torre": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Totem": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Tronco Gigante": ["Foresta", "Montagna", "Collina", "Prateria", "Palude"],
    "Trono": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Un castello": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Villaggio bruciato": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Villaggio distrutto": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"],
    "Vulcano": ["Foresta", "Montagna", "Collina", "Prateria", "Palude", "Deserto"]
}
